### ISSUE TITLE
Error 'model_state' in node BOPBTL_LoadScratchMaskModel

### ISSUE THREAD

**Issue by alepolisel** [cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life#20]
Hello, friends

First of all, thank you very much for the module. I'm just starting out with AI and comfyui, and seeing developments like this makes the path for newbies like me easier.

I created the bopbtl-full-workflow-512.png example and got the error below when generating it. I thought it might be the python version and downgraded it to version 3.10, but the error still persists. Am I doing something wrong? Can you help me?

`
# ComfyUI Error Report
## Error Details
- **Node Type:** BOPBTL_LoadScratchMaskModel
- **Exception Type:** KeyError
- **Exception Message:** 'model_state'
## Stack Trace
```
  File "E:\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 81, in run
    return BOPBTL_LoadScratchMaskModel.load_model(model_path)

  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 71, in load_model
    model = ScratchDetector.load_model(

  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\Global\detection.py", line 96, in load_model
    model.load_state_dict(checkpoint["model_state"])

```
## System Information
- **ComfyUI Version:** v0.2.1-5-g5cbaa9e
- **Arguments:** main.py
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8585084928
  - **VRAM Free:** 6978070084
  - **Torch VRAM Total:** 469762048
  - **Torch VRAM Free:** 16574020

## Logs
```
2024-09-05 18:50:39,327 - root - INFO - Total VRAM 8187 MB, total RAM 32688 MB
2024-09-05 18:50:39,327 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-05 18:50:39,329 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-05 18:50:39,329 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
2024-09-05 18:50:40,351 - root - INFO - Using pytorch cross attention
2024-09-05 18:50:41,261 - root - INFO - [Prompt Server] web root: E:\ComfyUI\web
2024-09-05 18:50:41,264 - root - INFO - Adding extra search path checkpoints E:\ComfyUI\models/Stable-diffusion
2024-09-05 18:50:41,264 - root - INFO - Adding extra search path configs E:\ComfyUI\models/Stable-diffusion
2024-09-05 18:50:41,264 - root - INFO - Adding extra search path vae E:\ComfyUI\models/VAE
2024-09-05 18:50:41,265 - root - INFO - Adding extra search path loras E:\ComfyUI\models/Lora
2024-09-05 18:50:41,265 - root - INFO - Adding extra search path loras E:\ComfyUI\models/LyCORIS
2024-09-05 18:50:41,266 - root - INFO - Adding extra search path upscale_models E:\ComfyUI\models/ESRGAN
2024-09-05 18:50:41,266 - root - INFO - Adding extra search path upscale_models E:\ComfyUI\models/RealESRGAN
2024-09-05 18:50:41,267 - root - INFO - Adding extra search path upscale_models E:\ComfyUI\models/SwinIR
2024-09-05 18:50:41,267 - root - INFO - Adding extra search path embeddings E:\ComfyUI\embeddings
2024-09-05 18:50:41,267 - root - INFO - Adding extra search path hypernetworks E:\ComfyUI\models/hypernetworks
2024-09-05 18:50:41,268 - root - INFO - Adding extra search path controlnet E:\ComfyUI\models/ControlNet
2024-09-05 18:50:42,120 - root - WARNING - Traceback (most recent call last):
  File "E:\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\custom_nodes\ComfyUI-dnl13-seg\__init__.py", line 21, in <module>
    from .index import NODE_CLASS_MAPPINGS
  File "E:\ComfyUI\custom_nodes\ComfyUI-dnl13-seg\index.py", line 8, in <module>
    from .nodes.node_modelloader_dinov1 import GroundingDinoModelLoaderV1
  File "E:\ComfyUI\custom_nodes\ComfyUI-dnl13-seg\nodes\node_modelloader_dinov1.py", line 1, in <module>
    from ..node_fnc.node_modelloader_dino import list_groundingdino_model, load_groundingdino_model
  File "E:\ComfyUI\custom_nodes\ComfyUI-dnl13-seg\node_fnc\node_modelloader_dino.py", line 6, in <module>
    from groundingdino.util.utils import clean_state_dict as local_groundingdino_clean_state_dict
ModuleNotFoundError: No module named 'groundingdino'

2024-09-05 18:50:42,121 - root - WARNING - Cannot import E:\ComfyUI\custom_nodes\ComfyUI-dnl13-seg module for custom nodes: No module named 'groundingdino'
2024-09-05 18:50:42,812 - root - INFO - 
Import times for custom nodes:
2024-09-05 18:50:42,812 - root - INFO -    0.0 seconds: E:\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-05 18:50:42,813 - root - INFO -    0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
2024-09-05 18:50:42,813 - root - INFO -    0.0 seconds (IMPORT FAILED): E:\ComfyUI\custom_nodes\ComfyUI-dnl13-seg
2024-09-05 18:50:42,813 - root - INFO -    0.0 seconds: E:\ComfyUI\custom_nodes\failfast-comfyui-extensions
2024-09-05 18:50:42,814 - root - INFO -    0.0 seconds: E:\ComfyUI\custom_nodes\comfy-image-saver
2024-09-05 18:50:42,814 - root - INFO -    0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-05 18:50:42,815 - root - INFO -    0.0 seconds: E:\ComfyUI\custom_nodes\rgthree-comfy
2024-09-05 18:50:42,816 - root - INFO -    0.0 seconds: E:\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-05 18:50:42,816 - root - INFO -    0.0 seconds: E:\ComfyUI\custom_nodes\comfyui-old-photo-restoration
2024-09-05 18:50:42,816 - root - INFO -    0.1 seconds: E:\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-05 18:50:42,817 - root - INFO -    0.2 seconds: E:\ComfyUI\custom_nodes\ComfyUI_DDColor
2024-09-05 18:50:42,817 - root - INFO -    0.3 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-05 18:50:42,818 - root - INFO -    0.5 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life
2024-09-05 18:50:42,820 - root - INFO - 
2024-09-05 18:50:42,829 - root - INFO - Starting server

2024-09-05 18:50:42,829 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-05 18:50:49,038 - root - INFO - got prompt
2024-09-05 18:50:55,621 - root - ERROR - !!! Exception during processing !!! 'model_state'
2024-09-05 18:50:55,622 - root - ERROR - Traceback (most recent call last):
  File "E:\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 81, in run
    return BOPBTL_LoadScratchMaskModel.load_model(model_path)
  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 71, in load_model
    model = ScratchDetector.load_model(
  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\Global\detection.py", line 96, in load_model
    model.load_state_dict(checkpoint["model_state"])
KeyError: 'model_state'

2024-09-05 18:50:55,623 - root - INFO - Prompt executed in 6.57 seconds
2024-09-05 18:52:14,836 - root - INFO - got prompt
2024-09-05 18:52:15,221 - root - ERROR - !!! Exception during processing !!! 'model_state'
2024-09-05 18:52:15,221 - root - ERROR - Traceback (most recent call last):
  File "E:\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 81, in run
    return BOPBTL_LoadScratchMaskModel.load_model(model_path)
  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 71, in load_model
    model = ScratchDetector.load_model(
  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\Global\detection.py", line 96, in load_model
    model.load_state_dict(checkpoint["model_state"])
KeyError: 'model_state'

2024-09-05 18:52:15,223 - root - INFO - Prompt executed in 0.37 seconds
2024-09-05 19:02:59,644 - root - INFO - got prompt
2024-09-05 19:03:00,059 - root - ERROR - !!! Exception during processing !!! 'model_state'
2024-09-05 19:03:00,059 - root - ERROR - Traceback (most recent call last):
  File "E:\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 81, in run
    return BOPBTL_LoadScratchMaskModel.load_model(model_path)
  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\nodes.py", line 71, in load_model
    model = ScratchDetector.load_model(
  File "E:\ComfyUI\custom_nodes\ComfyUI-Bringing-Old-Photos-Back-to-Life\Global\detection.py", line 96, in load_model
    model.load_state_dict(checkpoint["model_state"])
KeyError: 'model_state'

2024-09-05 19:03:00,061 - root - INFO - Prompt executed in 0.40 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":19,"nodes":[{"id":7,"type":"BOPBTL_LoadFaceDetectorModel","pos":{"0":2232,"1":170,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":390.5999755859375,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"dlib_model","type":"DLIB_MODEL","links":[5],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"BOPBTL_LoadFaceDetectorModel"},"widgets_values":["shape_predictor_68_face_landmarks.dat"]},{"id":8,"type":"BOPBTL_LoadFaceEnhancerModel","pos":{"0":2274,"1":332,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":106},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"face_enhance_model","type":"FACE_ENHANCE_MODEL","links":[6],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"BOPBTL_LoadFaceEnhancerModel"},"widgets_values":["0","Setting_9_epoch_100\\latest_net_G.pth","512"]},{"id":12,"type":"Stage1S","pos":{"0":2067,"1":43,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":529.199951171875,"1":82},"flags":{},"order":2,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":null}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":null,"shape":3}],"properties":{"Node name for S&R":"Stage1S"},"widgets_values":[false,"0"]},{"id":4,"type":"BOPBTL_LoadRestoreOldPhotosModel","pos":{"0":1744,"1":138,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":365.4000244140625,"1":178},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"bopbtl_models","type":"BOPBTL_MODELS","links":[8],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"BOPBTL_LoadRestoreOldPhotosModel"},"widgets_values":["0","True","True","Setting_9_epoch_100\\latest_net_G.pth","restoration\\VAE_B_scratch\\latest_net_G.pth","restoration\\VAE_A_quality\\latest_net_G.pth"]},{"id":11,"type":"LoadImage","pos":{"0":1212,"1":476,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":314},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[16],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["Imagem do WhatsApp de 2024-09-05 à(s) 08.21.56_e99942a1.jpg","image"]},{"id":14,"type":"ImageCrop","pos":{"0":1623,"1":690,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":130},"flags":{},"order":6,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":16}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[17,18],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"ImageCrop"},"widgets_values":[512,1024,0,0]},{"id":9,"type":"BOPBTL_RestoreOldPhotos","pos":{"0":2350,"1":549,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":241.79998779296875,"1":66},"flags":{},"order":8,"mode":0,"inputs":[{"name":"bopbtl_models","type":"BOPBTL_MODELS","link":8},{"name":"image","type":"IMAGE","link":18},{"name":"scratch_mask","type":"MASK","link":11}],"outputs":[{"name":"image","type":"IMAGE","links":[7],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"BOPBTL_RestoreOldPhotos"}},{"id":6,"type":"BOPBTL_ScratchMask","pos":{"0":1848,"1":467,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":102},"flags":{},"order":7,"mode":0,"inputs":[{"name":"scratch_model","type":"SCRATCH_MODEL","link":15},{"name":"image","type":"IMAGE","link":17}],"outputs":[{"name":"mask","type":"MASK","links":[11],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"BOPBTL_ScratchMask"},"widgets_values":["scale_256","lanczos"]},{"id":5,"type":"BOPBTL_LoadScratchMaskModel","pos":{"0":1331,"1":191,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":315,"1":58},"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"scratch_model","type":"SCRATCH_MODEL","links":[15],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"BOPBTL_LoadScratchMaskModel"},"widgets_values":["latest_optimizer_mapping_net.pth"]},{"id":10,"type":"BOPBTL_DetectEnhanceBlendFaces","pos":{"0":2721,"1":345,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":415.8000183105469,"1":66},"flags":{},"order":9,"mode":0,"inputs":[{"name":"dlib_model","type":"DLIB_MODEL","link":5},{"name":"face_enhance_model","type":"FACE_ENHANCE_MODEL","link":6},{"name":"image","type":"IMAGE","link":7}],"outputs":[{"name":"image","type":"IMAGE","links":[19],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"BOPBTL_DetectEnhanceBlendFaces"}},{"id":15,"type":"PreviewImage","pos":{"0":3276,"1":347,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0},"size":{"0":210,"1":26},"flags":{},"order":10,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":19}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}}],"links":[[5,7,0,10,0,"DLIB_MODEL"],[6,8,0,10,1,"FACE_ENHANCE_MODEL"],[7,9,0,10,2,"IMAGE"],[8,4,0,9,0,"BOPBTL_MODELS"],[11,6,0,9,2,"MASK"],[15,5,0,6,0,"SCRATCH_MODEL"],[16,11,0,14,0,"IMAGE"],[17,14,0,6,1,"IMAGE"],[18,14,0,9,1,"IMAGE"],[19,10,0,15,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9229599817706823,"offset":[-2071.680641357611,-33.839539576839]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
`

**Comment by cdb-boop** [comment]
It appears you are using the wrong scratch model. That's why it's unable to load the `model_state`.

Are you using the correct scratch mask model? Try the `scratch_detection\FT_Epoch_latest` and set the ScratchMask node `input_size` to `full_size`.

Also, are you using the correct `mapping_net` in the `Load Restore Old Photos Model`? It looks like you are using the face enhancer model instead of the whole image restoration model.

Take a close look at each of the node inputs in the [example workflow image](https://github.com/cdb-boop/ComfyUI-Bringing-Old-Photos-Back-to-Life/blob/master/imgs/bopbtl-full-workflow-512.png) to make sure you're using the correct inputs.

**Comment by alepolisel** [comment]
Really. I'm really sorry. It works fine now.
